package com.example.astro.api;

import com.example.astro.api.dto.AstronautDto;
import com.example.astro.api.mapper.AstronautMapper;
import com.example.astro.service.AstronautService;
import jakarta.validation.constraints.Pattern;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.parameters.RequestBody;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;

import java.net.URI;
import java.time.LocalDate;
import java.util.List;
import java.util.stream.Collectors;

@RestController
@RequestMapping("/astronauts")
@Validated
@Tag(name = "Astronauts", description = "Operations for querying and managing astronauts and their ISS missions.")
public class AstronautController {

  private final AstronautService service;
  private final AstronautMapper mapper;

  public AstronautController(AstronautService service, AstronautMapper mapper) {
    this.service = service;
    this.mapper = mapper;
  }

  @GetMapping
  @Operation(
    summary = "Get astronauts by ISS range",
    description = "Returns astronauts that have at least one ISS mission overlapping the given date range. " +
      "If dateTo is omitted, it defaults to today. Each astronaut includes total ISS time and days within the range."
  )
  @ApiResponses({
    @ApiResponse(responseCode = "200", description = "Astronauts found"),
    @ApiResponse(responseCode = "400", description = "Invalid date range")
  })
  public ResponseEntity<List<AstronautDto>> getByRange(
      @RequestParam("dateFrom") @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate dateFrom,
      @RequestParam(value = "dateTo", required = false) @DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate dateTo
  ) {
    LocalDate to = (dateTo == null) ? LocalDate.now() : dateTo;
    if (to.isBefore(dateFrom)) {
      return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
    }
    List<AstronautDto> result = service.findByRange(dateFrom, to).stream()
      .map(a -> mapper.toDtoWithinRange(a, dateFrom, to))
      .collect(Collectors.toList());
    return ResponseEntity.ok(result);
  }

  @GetMapping("/{id}")
  @Operation(summary = "Get astronaut by id", description = "Returns a single astronaut by identifier.")
  @ApiResponses({
    @ApiResponse(responseCode = "200", description = "Astronaut found"),
    @ApiResponse(responseCode = "404", description = "Astronaut not found")
  })
  public ResponseEntity<AstronautDto> getById(
      @PathVariable("id")
      @Pattern(regexp = "^[A-Za-z0-9\\-]+$", message = "Invalid id") String id
  ) {
    return service.getById(id)
      .map(mapper::toDto)
      .map(ResponseEntity::ok)
      .orElseGet(() -> ResponseEntity.status(HttpStatus.NOT_FOUND).build());
  }

  @PostMapping
  @Operation(
    summary = "Create a new astronaut",
    description = "Creates a new astronaut with ISS missions. The id is generated by the service."
  )
  @ApiResponses({
    @ApiResponse(responseCode = "201", description = "Astronaut created"),
    @ApiResponse(responseCode = "400", description = "Invalid request body")
  })
  public ResponseEntity<AstronautDto> createAstronaut(
    @RequestBody(
      required = true,
      description = "Astronaut payload without id; missions and dates must be valid.",
      content = @Content(
        schema = @Schema(implementation = AstronautDto.class),
        examples = @ExampleObject(
          name = "CreateAstronautRequest",
          summary = "Sample astronaut create payload",
          value = """
            {
              "firstName": "John",
              "lastName": "Doe",
              "dateOfBirth": "1980-01-01",
              "missions": [
                {
                  "missionName": "Expedition 99",
                  "startDate": "2025-01-01",
                  "endDate": "2025-06-01"
                }
              ]
            }
            """
        )
      )
    )
    @org.springframework.web.bind.annotation.RequestBody AstronautDto body
  ) {
    var prototype = mapper.toDomain(body);
    var created = service.create(prototype);
    var dto = mapper.toDto(created);
    URI location = URI.create("/astronauts/" + dto.id);
    return ResponseEntity.created(location).body(dto);
  }

  @PutMapping("/{id}")
  @Operation(
    summary = "Update an astronaut",
    description = "Replaces the astronaut data for the given id. Returns 404 if the astronaut does not exist."
  )
  @ApiResponses({
    @ApiResponse(responseCode = "200", description = "Astronaut updated"),
    @ApiResponse(responseCode = "404", description = "Astronaut not found")
  })
  public ResponseEntity<AstronautDto> updateAstronaut(
    @PathVariable("id")
    @Pattern(regexp = "^[A-Za-z0-9\\-]+$", message = "Invalid id") String id,
    @RequestBody(
      required = true,
      description = "Updated astronaut payload; id in body is ignored, path id is used.",
      content = @Content(
        schema = @Schema(implementation = AstronautDto.class),
        examples = @ExampleObject(
          name = "UpdateAstronautRequest",
          summary = "Sample astronaut update payload",
          value = """
            {
              "firstName": "John",
              "lastName": "Doe",
              "dateOfBirth": "1980-01-01",
              "missions": [
                {
                  "missionName": "Expedition 99",
                  "startDate": "2025-01-01",
                  "endDate": "2025-06-01"
                }
              ]
            }
            """
        )
      )
    )
    @org.springframework.web.bind.annotation.RequestBody AstronautDto body
  ) {
    var prototype = mapper.toDomain(body);
    return service.update(id, prototype)
      .map(mapper::toDto)
      .map(ResponseEntity::ok)
      .orElseGet(() -> ResponseEntity.status(HttpStatus.NOT_FOUND).build());
  }

  @DeleteMapping("/{id}")
  @Operation(
    summary = "Delete an astronaut",
    description = "Deletes the astronaut with the given id. Returns 204 on success, 404 if not found."
  )
  @ApiResponses({
    @ApiResponse(responseCode = "204", description = "Astronaut deleted"),
    @ApiResponse(responseCode = "404", description = "Astronaut not found")
  })
  public ResponseEntity<Void> deleteAstronaut(
    @PathVariable("id")
    @Pattern(regexp = "^[A-Za-z0-9\\-]+$", message = "Invalid id") String id
  ) {
    boolean deleted = service.delete(id);
    if (deleted) {
      return ResponseEntity.noContent().build();
    }
    return ResponseEntity.status(HttpStatus.NOT_FOUND).build();
  }
}


